# Code Snapshot Configuration
input:
  file: "./example.dart"
  startLine: 37
  endLine: 46

output:
  path: "./code-snapshot.png"
  width: null
  height: null

styling:
  cardTransparency: 0.8
  backgroundColor: "#1e3a8a"
  gradientMiddleColor: "#3b82f6"
  showLineNumbers: true
  showFileName: true
  windowControl: "hidden"
  cardMargin:
    horizontal: 40
    vertical: 40
