# Code Snapshot Configuration
input:
  file: "./example.dart"
  startLine: 37
  endLine: 46

output:
  path: "./code-snapshot.png"
  width: null
  height: null

styling:
  cardTransparency: 0.8
  background:
    type: "filled"
    color: "#1e3a8a"
  showLineNumbers: true
  showFileName: true
  windowControl: "hidden"
  cardMargin:
    horizontal: 40
    vertical: 40
  borderRadius: 25
  imageBorderRadius: 40
