# Code Snapshot Configuration
input:
  file: "./example.dart"
  startLine: 37
  endLine: 46
  lints:
    - start: { line: 38, char: 3 }
      end: { line: 38, char: 7 }
      type: error
      message: "Unused variable"
    - start: { line: 40, char: 1 }
      end: { line: 40, char: 8 }
      type: error
      message: "Missing await"

output:
  path: "./code-snapshot.png"
  width: null
  height: null

styling:
  cardTransparency: 0.8
  background:
    type: "filled"
    color: "#1e3a8a"
  showLineNumbers: true
  fileName: "index.dart"
  fileIcon: null # Path to custom icon file (e.g., "./assets/dart-icon.png")
  windowControl: "outlined"
  cardMargin:
    horizontal: 40
    vertical: 40
  borderRadius: 25
  imageBorderRadius: 40
