# Code Snapshot Configuration
input:
  file: "./example.dart"
  startLine: 37
  endLine: 46
  lints:
    - start: { line: 38, char: 3 }
      end: { line: 38, char: 7 }
      type: error
      message: "Unused variable"
    - start: { line: 40, char: 1 }
      end: { line: 40, char: 8 }
      type: error
      message: "Missing await"

output:
  path: "./code-snapshot.png"
  width: null
  height: null

styling:
  cardBackground:
    type: "layered"
    transparency: 0.3
    partialTransparency: 0.3 # How much more transparent the overlay should be
    color: "#22c55e" # Green color for main overlay
    partialBackgroundColor: "#d3d3d3" # Light gray color for full background
  background:
    type: "gradient"
    colors:
      - color: "#ffffff"
        stop: 0.0
      - color: "#3b82f6"
        stop: 1.0
    direction: to-bottom-right
  showLineNumbers: true
  lineNumberStart: 1 # Starting line number (defaults to 1)
  showLintMessages: false
  fileName: "index.dart"
  fileIcon: null # Path to custom icon file (e.g., "./assets/dart-icon.png")
  windowControl: "outlined"
  cardMargin:
    horizontal: 80
    vertical: 80
  borderRadius: 16
  imageBorderRadius: 25
