# Code Snapshot Configuration
input:
  file: "./example.dart"
  startLine: 37
  endLine: 46
  lints:
    - start: { line: 38, char: 3 }
      end: { line: 38, char: 7 }
      type: error
      message: "Unused variable"
    - start: { line: 40, char: 1 }
      end: { line: 40, char: 8 }
      type: error
      message: "Missing await"

output:
  path: "./code-snapshot.png"
  width: null
  height: null

styling:
  windowControl: hidden
  cardBackground:
    type: "layered"
    transparency: 0.3
    partialTransparency: 0.5 # How much more transparent the overlay should be
    showBlur: false # Whether to show blur effect on the slanted edge
    color: "#44475a" # Dracula selection
    partialBackgroundColor: "#282a36" # Dracula background
  background:
    type: "gradient"
    colors:
      - color: "#282a36"
        stop: 0.0
      - color: "#44475a"
        stop: 1.0
    direction: to-bottom-right
  showLineNumbers: true
  lineNumberStart: 1 # Starting line number (defaults to 1)
  showLintMessages: false
  fileName: "index.dart"
  fileIcon: null # Path to custom icon file (e.g., "./assets/dart-icon.png")
  cardMargin:
    horizontal: 80
    vertical: 80
  borderRadius: 16
  imageBorderRadius: 25
  tokenColors:
    keyword: "#ff79c6" # Dracula pink
    function: "#50fa7b" # Dracula green
    method: "#50fa7b" # Dracula green (same as function)
    string: "#f1fa8c" # Dracula yellow
    number: "#bd93f9" # Dracula purple
    comment: "#6272a4" # Dracula comment
    class-name: "#8be9fd" # Dracula cyan
    variable: "#f8f8f2" # Dracula foreground
    operator: "#ff79c6" # Dracula pink
    punctuation: "#f8f8f2" # Dracula foreground
    expression: "#f8f8f2"
