# Example Configuration with Different Styling
input:
  file: "./example.dart"
  startLine: 37
  endLine: 46

output:
  path: "./example-snapshot.png"
  width: 900
  height: 700

styling:
  cardTransparency: 0.6 # More transparent card
  showWindowControls: true
  backgroundColor: "#1e40af" # Slightly different blue
  gradientMiddleColor: "#60a5fa" # Lighter middle color
